spring.application.name=model
# ---------- Database ----------
spring.datasource.url=jdbc:mysql://localhost:3306/eparking_db
spring.datasource.username=nandhini
spring.datasource.password=@Nandy07

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ---------- Billing ----------
billing.rate.per.hour=20.00

server.port=8080